### ISSUE TITLE
Let's challenge

### ISSUE THREAD

**Issue by Datez-Kun** [htr-tech/Reverse-Engineering#1]
I see this repository is quite interesting, it looks like you re-upload the files in my repository (just don't expect to get angry), I have a challenge that is quite interesting, if you are really great and good at python / breaking code, the challenge is  pretty easy, you just need to find the original code I made that I compiled, I give you a day after you see this issue 😀 If it doesn't work then I will assume you have re-uploaded the file in my repository
##### python 2.7
[This Files](https://github.com/Datez-Kun/reverse-enginnering/blob/master/MyRepo/my.py)

**Comment by htr-tech** [comment]
@Datez-Kun  Bro i am a part time coder . I can decompile only the weak scripts . i am not a pro like u. 

[Decoded Script](https://throwbin.io/GWrpakn)

Please decrypt the scripts of This person if u can .

https://gitlab.com/Sumarr-ID
https://gitlab.com/Sumarr-ID/anti
https://gitlab.com/Sumarr-ID/enc


Love from BD

**Comment by Datez-Kun** [comment]
> @Datez-Kun Bro i am a part time coder . I can decompile only the weak scripts . i am not a pro like u.
> 
> [Decoded Script](https://throwbin.io/GWrpakn)
> 
> Please decrypt the scripts of This person if u can .
> 
> https://gitlab.com/Sumarr-ID
> https://gitlab.com/Sumarr-ID/anti
> https://gitlab.com/Sumarr-ID/enc
> 
> Love from BD

This ,..
https://raw.githubusercontent.com/Datez-Kun/reverse-enginnering/master/anti/out.py
https://raw.githubusercontent.com/Datez-Kun/reverse-enginnering/master/enc/enc_open.py

**Comment by htr-tech** [comment]
Bro please decrypt these Repositories ... Plzzz

https://github.com/Binyamin-binni/binni
