### ISSUE TITLE
Cool

### ISSUE THREAD

**Issue by CybernetiX-S3C** [htr-tech/Reverse-Engineering#2]
So these are tools you renamed and changed framework info to be able to claim as your own. 

Not reverse engineering. You just opened the original script, and added your name.

**Comment by htr-tech** [comment]
@CybernetiX-S3C no bro .. i just decoded & uploaded it ... i dont claim these scripts as mine 😩 

& these projects have been moved to https://github.com/hax0rtahm1d/Reverse-Engineering
